remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//fp-ts.github.io/data"
  "API Reference":
    - "//fp-ts.github.io/data/docs/modules"
  "GitHub":
    - "//github.com/fp-ts/data"
